name: CI Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt --only-binary :all:
        pip install flake8 pytest

    - name: Lint with flake8
      run: |
        flake8 . --max-line-length=88 --extend-ignore=E203 --exclude=./api/venv,./monitoring/venv,./.venv

    - name: Test with pytest
      run: |
        pytest